# 5.3.1 retrying - 模块

我们在写一些程序的时候，会去调用一些外部资源、组件，这些外部程序对我们来说是不可控的，所以它们不可用、运行失败都是正常的事情，尤其是在网络上多个服务交互的时候，在写程序的时候一定要考虑调用外部程序会失败的情况。

_retrying_就是一个可以用来应对上述问题的工具，可以在[PyPi](https://pypi.python.org/pypi/retrying)上获得。<br />_retrying_提供一个装饰器函数`retry`，被装饰的函数就会在运行失败的条件下重新执行，默认只要一直报错就会不断重试
